### ISSUE TITLE
Can you provide support for node v18？

### ISSUE THREAD

**Issue by Suo-Ran** [yjl9903/naria2#354]
### Clear and concise description of the problem

I'm using @naria2/node for my electron applications to automatically build the system version for cross-platform use. However, even the latest stable version of electron does not have node versions up to V20, and there are still many bugs to be fixed in 26, 27, and 28, so node V18 is still a very high share of electron applications. Is it possible to support @naria2/node over v18?

**Comment by yjl9903** [comment]
I think this package does not use any latest node features. So it should work in node v18?

And I am not very familiar with electron. I don't know how electron bundle your desktop app? @naria2/node does things like other native packages like esbuild, swc, that it includes different binary deps for different platform (see https://github.com/yjl9903/naria2/tree/main/packages/binary)

Maybe I can republish it changing node version to v18?

**Comment by Suo-Ran** [comment]
> I think this package does not use any latest node features. So it should work in node v18?
> 
> And I am not very familiar with electron. I don't know how electron bundle your desktop app? @naria2/node does things like other native packages like esbuild, swc, that it includes different binary deps for different platform (see https://github.com/yjl9903/naria2/tree/main/packages/binary)
> 
> Maybe I can republish it changing node version to v18? Or can you provide more information or minial reproduction for further debugging?

I ran it independently and found that it didn't work with node v18, which is v18.16.0
Here's my test code:

index.js

```javascript
import { createClient } from "naria2";
import { createChildProcess } from "@naria2/node";

const client = await createClient(createChildProcess());

console.log(client.options);
```

package.json

```json
{
  "name": "test-naria2-node",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "",
  "type": "module",
  "license": "ISC",
  "dependencies": {
    "@naria2/node": "^0.0.24",
    "naria2": "^0.0.24"
  }
}
```

**Comment by yjl9903** [comment]
Maybe it is related with the upstream library maria2. It does some polyfill to support different platforms.

**Comment by yjl9903** [comment]
I patch maria2 manually, could you try the latest 0.0.25?

Related issue: https://github.com/hydrati/maria2/pull/15

**Comment by Suo-Ran** [comment]
> I patch maria2 manually, could you try the latest 0.0.25?
> 
> Related issue: [hydrati/maria2#15](https://github.com/hydrati/maria2/pull/15)

Unfortunately, the result is the same. My node version is v18.16.0

**Comment by Suo-Ran** [comment]
> In my env, it works ok :(
> 
> ```
> $ pnpm dlx envinfo --system --binaries --browsers
>   System:
>     OS: macOS 14.2.1
>     CPU: (8) arm64 Apple M1
>     Memory: 39.78 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 18.16.0 - ~/Library/Caches/fnm_multishells/52082_1705906398782/bin/node
>     npm: 9.5.1 - ~/Library/Caches/fnm_multishells/52082_1705906398782/bin/npm
>     pnpm: 8.14.1 - ~/Library/pnpm/pnpm
>   Browsers:
>     Safari: 17.2.1
> ```

This is my env, it looks like it should be a matter of operating system differences, mine is PC
```cmd
  System:
    OS: Windows 11 10.0.22621
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 39.48 GB / 63.76 GB
  Binaries:
    Node: 18.16.0 - ~\software\nodejs\node.EXE
    Yarn: 1.22.19 - ~\software\nodejs\yarn.CMD
    npm: 9.5.1 - ~\software\nodejs\npm.CMD
    pnpm: 8.6.5 - ~\software\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
```

**Comment by Suo-Ran** [comment]
It still stops running here
https://github.com/hydrati/maria2/blob/764c038a50d33a086fe1377dbe3327636a9e9544/src/shared.ts#L24

**Comment by Suo-Ran** [comment]
It still stops running here
![image](https://github.com/yjl9903/naria2/assets/60297886/b59592af-4dae-437b-99c4-d948c4a94357)

https://github.com/hydrati/maria2/blob/764c038a50d33a086fe1377dbe3327636a9e9544/src/shared.ts#L24

**Comment by Suo-Ran** [comment]
> I patch maria2 manually, could you try the latest 0.0.25?
> 
> Related issue: [hydrati/maria2#15](https://github.com/hydrati/maria2/pull/15)

Looks like it's not merging pr

**Comment by yjl9903** [comment]
> > I patch maria2 manually, could you try the latest 0.0.25?
> > Related issue: [hydrati/maria2#15](https://github.com/hydrati/maria2/pull/15)
> 
> Looks like it's not merging pr

I have patched the package, so naria2 is not affected by the upstream. I am not sure whether patch works. 

Since that PR have merged, I will upgrade it tonight.

**Comment by Suo-Ran** [comment]
> > > I patch maria2 manually, could you try the latest 0.0.25?
> > > Related issue: [hydrati/maria2#15](https://github.com/hydrati/maria2/pull/15)
> > 
> > 
> > Looks like it's not merging pr
> 
> I have patched the package, so naria2 is not affected by the upstream. I am not sure whether patch works.
> 
> Since that PR have merged, I will upgrade it tonight.

I cloned the code, the local link was running successfully, but the download from npm still executed that part of the code, it seems that the patch is not fully effective

**Comment by yjl9903** [comment]
I will upgrade naria2 after maria2 being published this Sat, for now you can do similiar patch in your project.

**Comment by Suo-Ran** [comment]
> I will upgrade naria2 after maria2 being published this Sat, for now you can do similiar patch in your project.

When is the next release scheduled, since it's been a while :)

**Comment by yjl9903** [comment]
For the upstream maria2 has not been updated...

**Comment by yjl9903** [comment]
It should be resolved in https://github.com/hydrati/maria2/commit/4947c12da93ad186f7ce2db31a0c0678d53b6e21

and naria2 0.0.26
