### ISSUE TITLE
示例有误

### ISSUE THREAD

**Issue by Rewrite0** [yjl9903/naria2#497]
### Describe the bug

根据 [aria2的文档](https://aria2.github.io/manual/en/html/aria2c.html#aria2.addTorrent)，磁力链接需要用 `addUri` 方法，[示例](https://github.com/yjl9903/naria2/blob/c99c262f3b4848ba2d349cdab1803663a6b6861f/scripts/download.mjs#L22)用的 `downloadTorrent` 方法底层调用的是 [addTorrent](https://github.com/yjl9903/naria2/blob/c99c262f3b4848ba2d349cdab1803663a6b6861f/packages/naria2/src/client/client.ts#L112)，而原文描述为 ` torrent must be a base64-encoded string containing the contents of the ".torrent" file.`

实际上示例也确实跑不起来 
![image](https://github.com/user-attachments/assets/70ef5040-a52e-49e7-b94f-ec58820de702)

如果我用 `addUri` 方法下载磁力链接，则没有 `watchFollowedBy` 方法.
![image](https://github.com/user-attachments/assets/590bc532-f3d2-4f0b-9fed-495a44c337e4)

请问如何正确下载磁力链?

### Used Package Manager

pnpm

**Comment by yjl9903** [comment]
我调整一下 API

**Comment by yjl9903** [comment]
https://github.com/yjl9903/naria2/commit/4339a7536bfa29aece140e60dbb6275792ccdc5a
