### ISSUE TITLE
downloadTorrent 方法使用问题

### ISSUE THREAD

**Issue by Rewrite0** [yjl9903/naria2#576]
### Describe the bug

我按照aria2的文档，读取torrent文件的内容并转为base64
但是downloadTorrent方法一直返回 `Naria2Error: The parameter at 1 has wrong type.`

![image](https://github.com/user-attachments/assets/c13ae7c3-b432-4bc8-bdd0-16dbd7383f72)
![image](https://github.com/user-attachments/assets/ffdb4456-ab64-487b-bd21-da3a674acc58)

### Used Package Manager

None

**Comment by yjl9903** [comment]
Resolved in https://github.com/yjl9903/naria2/commit/66e69cb0f0d9ac384055466dc60fa979c40945d0

**Comment by Rewrite0** [comment]
辛苦了
